repos:
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ['--filter-files']
        minimum_pre_commit_version: '2.9.2'
        additional_dependencies: [isort==5.10.1]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ".*?(.hex|.clvm|.clib)"
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        additional_dependencies: ['click<8.1']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
